### PR TITLE
Move config to models.__init__ (Issue #48)

### LINKED ISSUE #48: Import config in every model
**Problem:**  whenever a model is to be used, we have to import the config module as well. This is unintuitive and could let to duplication sparse in the code.

**Possible solution:**  import db config in every model.

### PR DESCRIPTION
**Pull request by ribeirojose**
fixes #48 .

### CODE REVIEW

**Comment by lukasab** [comment]
I will check later if all keeps working.

**Comment by ribeirojose** [comment]
> I will check later if all keeps working.

Tests plz

**Comment by ribeirojose** [comment]
Note to self: fix TimeEntry missing config in `config.db`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ribeirojose** [comment]
@lukasab  any news here?

**Pull request merged**
